[package]
name = "handmade_ferris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
x11-rs     = { path = "./x11-rs" }
game_state = { path = "../game_state" }
vector     = { path = "../vector" }
